spring:
  application:
    name: kafka-performance-lab
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: orders-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      concurrency: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

